name: quick_spell
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  collection: ^1.19.0
  country_picker: ^2.0.21
  csslib: ^1.0.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  file_picker: ^10.1.9
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  firebase_performance: ^0.10.1+7
  firebase_storage: ^12.4.7
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.1
  flutter_plugin_android_lifecycle: ^2.0.28
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.3.0
  html: ^0.15.6
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_path: ^0.7.2
  mime_type: ^1.0.0
  page_transition: ^2.1.0
  path_provider: ^2.1.4
  percent_indicator: ^4.2.2
  provider: ^6.1.5
  rxdart: ^0.27.7
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  simple_gradient_text: ^1.2.3
  sqflite: ^2.3.3+1
  stop_watch_timer: ^3.0.2
  stream_transform: ^2.1.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  video_player: ^2.10.0
  
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: ^1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
